name: fogo_technical_test
description: Demonstrates how to use flutter_blue_plus and bloc plugins.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">3.0.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_blue_plus: ^1.35.5

flutter:
  uses-material-design: true
